// packages/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { createEmptyPage, DocEditor } from '@blocksuite/presets';
import '@blocksuite/presets/themes/affine.css';

console.assert(DocEditor !== undefined);

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'angular-blocksuite';

  async ngOnInit() {
    const page = await createEmptyPage().init();
    const editor = new DocEditor();
    const container = document.querySelector('.container') as HTMLElement;
    editor.page = page;
    container.appendChild(editor);
  }
}

// packages/nuxt/app.vue
<script setup lang="ts">
import '@blocksuite/presets/themes/affine.css';
import { createEmptyPage, DocEditor } from '@blocksuite/presets';

const container = ref<HTMLDivElement>();
const page = await createEmptyPage().init();
const editor = new DocEditor();
editor.page = page;
onMounted(() => {
  container.value!.append(editor);
});
</script>

<template>
  <div ref="container" class="editor-container" />
</template>

<style scoped>
.editor-container {
  width: 100vw;
  height: 100vh;
}
</style>
